=== MagliariElio/Distributed-Systems-Programming/EXAMPLE/schemaExamples/test1schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://dsp.polito.it/test1schema.json",
    "title": "This is the schema for a user record",
    "type": "object",
    "properties": {
        "firstname": { "type": "string", "maxLength": 10, "pattern": "E[a-z]*" },
        "lastname": { "type": "string", "maxLength": 10 },
        "birthdate": { "type": "string", "format": "date" },
        "addresses": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "street": { "type": "string" },
                        "city": { "type": "string" },
                        "country": { "type" : "string" }
                    }
            }
        }
    },
    "required": ["firstname","lastname"],
    "additionalProperties": {"type": "string", "pattern":"$[a-z]*"}
}

=== MagliariElio/Distributed-Systems-Programming/EXAMPLE/schemaExamples/test1.json
{
    "$schema":"./test1schema.json",
    "firstname": "Elton",
    "lastname": "John",
    "birthdate": "1947-03-25",
    "addresses": [{
        "street": "1 Blythe Road",
        "city": "London",
        "country": "UK"
    },{
        "street": "1 Blythe Road",
        "city": "London",
        "country": "UK"
    }]
}
